ln -s ~/git_projects/linux_conf/gitignore ~/.gitignore
ln -s ~/git_projects/linux_conf/gitconfig ~/.gitconfig
ln -s ~/git_projects/linux_conf/vi/vimrc ~/.vimrc
ln -s ~/git_projects/linux_conf/vi/vim ~/.vim
ln -s ~/git_projects/linux_conf/xmonad ~/.xmonad
ln -s ~/git_projects/linux_conf/xmobarrc ~/.xmobarrc
ln -s ~/git_projects/linux_conf/scripts ~/bin
ln -s ~/git_projects/linux_conf/bash_aliases ~/.bash_aliases
ln -s ~/git_projects/linux_conf/zshrc ~/.zshrc
