#!/bin/bash
export JAVA_OPTIONS="“-Dfile.encoding=UTF-8 -Dframework.database=$1 -Dframework.switchOnFullTextSearch=false -Dframework.log.dir=/home/dolanotoole/log -Djava.security.auth.login.config=/home/dolanotoole/wlsdomain/base_domain/config/jaas.config -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n -javaagent:/home/dolanotoole/wlsdomain/base_domain/lib/aspectjweaver.jar"
cd /home/dolanotoole/wlsdomain/base_domain/config/jdbc
ln -sf $1DS.txt OracleDS-0429-jdbc.xml
../../startWebLogic.sh
