#!/bin/bash
trayer --edge top --align right --margin 1440 --SetDockType true --SetPartialStrut true --expand true --width 5 --transparent true --tint 0x191970 --height 12 &
xscreensaver -no-splash &
gnome-power-manager &
wicd-gtk &
gnome-settings-daemon &
feh --bg-scale ~/Pictures/02482_gamut_2560x1600.jpg
#xcompmgr -cC &
wmname LG3D
