#!/bin/bash
tray &
xscreensaver -no-splash &
#gnome-power-manager &
#wicd-gtk &
gnome-settings-daemon &
gnome-sound-applet &
nm-applet &
# gnome-keyring-daemon &
feh --bg-scale ~/Pictures/01740_rockefellersview_1920x1200.jpg
#xcompmgr -cC &
wmname LG3D
#davmail &
#nautilus -n &
dropbox start
