#!/bin/bash
tray &
xscreensaver -no-splash &
#gnome-power-manager &
#wicd-gtk &
#gnome-settings-daemon &
#gnome-sound-applet &
nm-applet &
# gnome-keyring-daemon &
feh --bg-scale ~/Pictures/xmonad_1080p.png
#xcompmgr -cC &
wmname LG3D
#davmail &
#nautilus -n &
dropbox start
#xfce4-settings-helper --display :0.0
